# write a workflow of github action
#  to release two artifacts to action1 and action2 repos

name: Build and Release Artifacts

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build artifacts
        run: |
          mkdir -p artifacts/action1 artifacts/action2
          # 构建 action1 的制品
          echo "This is action1 artifact" > artifacts/action1/artifact1.txt
          # 构建 action2 的制品
          echo "This is action2 artifact" > artifacts/action2/artifact2.txt

      - name: Release to action1 repository
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: false
          artifacts: artifacts/action1/*
          artifactContentType: "raw"
          name: ${{ env.NIGHTLYDATETIME }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          owner: ${{ github.repository_owner }}	  
          prerelease: true
          replacesArtifacts: true
          repo: action1
          tag: nightly-${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release to action2 repository
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: false
          artifacts: artifacts/action2/*
          artifactContentType: "raw"
          name: ${{ env.NIGHTLYDATETIME }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          owner: ${{ github.repository_owner }}	  
          prerelease: true
          replacesArtifacts: true
          repo: action2
          tag: nightly-${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
