name: Arch AUR Repository Build

on:
  push:
  pull_request:
  schedule:
    - cron:  '1 7 * * 0'

jobs:
  # build-x86_64:
  #   runs-on: ubuntu-latest
  #   name: Build on x86_64

  #   container:
  #     image: archlinux:latest
  #     options: --privileged

  #     env:
  #       PKGEXT: .pkg.tar.zst

  #   steps:
  #     - name: Set variables
  #       id: set-vars
  #       run: |
  #         echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M')"
  #         echo "::set-output name=repo-id::$(echo ${{ github.repository }} | sed 's/\//-/g')"

  #     - name: Prepare repo
  #       id: prepare
  #       run: |
  #         echo "::set-output name=arch::$(uname -m)"
  #         pacman -Syyu --noconfirm
  #         pacman -S --noconfirm base-devel sudo
  #         echo 'auruser ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/auruser
  #         useradd -m auruser
  #         cd /tmp
  #         curl --output aurutils.tar.gz https://aur.archlinux.org/cgit/aur.git/snapshot/aurutils.tar.gz
  #         tar xf aurutils.tar.gz
  #         chmod -R 777 /tmp/aurutils
  #         cd aurutils
  #         sudo -u auruser makepkg --syncdeps --noconfirm
  #         pacman -U --noconfirm aurutils-*.pkg.*
  #         cp -v /tmp/aurutils/aurutils-*.pkg.* ${GITHUB_WORKSPACE}
  #         export REPO_IDENTIFIER="${{ steps.set-vars.outputs.repo-id }}"
  #         repo-add ${GITHUB_WORKSPACE}/${REPO_IDENTIFIER}.db.tar.gz ${GITHUB_WORKSPACE}/aurutils-*.pkg.*
  #         chmod -R 777 ${GITHUB_WORKSPACE}
  #         echo "# local repository (required by aur tools to be set up)" >> /etc/pacman.conf
  #         echo "[${REPO_IDENTIFIER}]" >> /etc/pacman.conf
  #         echo "SigLevel = Optional TrustAll" >> /etc/pacman.conf
  #         echo "Server = file://${GITHUB_WORKSPACE} " >> /etc/pacman.conf
  #         pacman -Sy --noconfirm
  #         # 在此处安装其他需要的包
  #         for pkg in emacs-git
  #         do
  #           echo "### Package ${pkg}"
  #           sudo -u auruser aur sync --noconfirm --noview --database ${REPO_IDENTIFIER} --root ${GITHUB_WORKSPACE} ${pkg} || echo "!!! Package ${pkg} failed"
  #         done
  #         chmod -R 777 ${GITHUB_WORKSPACE}

  #     - name: Remove symbolic links
  #       run: |
  #         cd ${GITHUB_WORKSPACE}
  #         ls -al
  #         rm -v ${{ steps.set-vars.outputs.repo-id }}.db ${{ steps.set-vars.outputs.repo-id }}.files
  #         cp -v ${{ steps.set-vars.outputs.repo-id }}.db.tar.gz ${{ steps.set-vars.outputs.repo-id }}.db
  #         cp -v ${{ steps.set-vars.outputs.repo-id }}.files.tar.gz ${{ steps.set-vars.outputs.repo-id }}.files
  #         rm -fv build-log.txt *.sh
  #         ls -al

  #     - name: Remove release
  #       uses: cb80/delrel@latest
  #       with:
  #         tag: ${{ steps.prepare.outputs.arch }}
  #         token: ${{ secrets.TOKEN }}

  #     - name: Upload release
  #       uses: ncipollo/release-action@v1
  #       with:
  #         tag: ${{ steps.prepare.outputs.arch }}
  #         name: Arch Linux AUR Build ${{ github.run_number }} from ${{ steps.set-vars.outputs.date }} for ${{ steps.prepare.outputs.arch }}
  #         body: |
  #           To use this repository, please append the following to `/etc/pacman.conf`:
  #           ```
  #           [${{ steps.set-vars.outputs.repo-id }}]
  #           SigLevel = Required
  #           Server = https://github.com/${{ github.repository }}/releases/download/${{ steps.prepare.outputs.arch }}
  #           ```
  #         artifacts: |
  #           ${{ github.workspace }}/*
  #         draft: false
  #         prerelease: false
  #         token: ${{ secrets.TOKEN }}

  build-arm:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: aarch64

    steps:
      # - name: Setup cache
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/.ccache
      #     key: build_ubuntu-18.04_${{ matrix.arch }}

      - name: Set variables
        id: set-vars
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M')"
          echo "::set-output name=repo-id::$(echo ${{ github.repository }} | sed 's/\//-/g')"

      - name: Check if release exists
        id: check_release
        run: |
          RELEASE_NAME="Arch Linux ARM AUR Build ${{ github.run_number }} from ${{ steps.set-vars.outputs.date }} for ${{ matrix.arch }}"
          API_URL="https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ matrix.arch }}"
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" $API_URL)
          if echo "$RESPONSE" | grep -q "\"id\":"; then
            echo "Release already exists. Exiting."
            echo "release_exists=true" >> $GITHUB_OUTPUT
          else
            echo "release_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Exit if release exists
        if: steps.check_release.outputs.release_exists == 'true'
        run: echo "Release already exists. Skipping build."

      - name: Prepare repo
        id: prepare
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: ${{ matrix.arch }}
          distro: archarm_latest
          githubToken: ${{ secrets.TOKEN }}
          # setup: |
          #   mkdir -p ~/.ccache
          dockerRunArgs: |
            --volume "${{ runner.temp }}:/workspace"
          #   --volume "${HOME}/.ccache:/root/.ccache"
          # install: |
          #   pacman -Syyu --noconfirm
          #   pacman -S --noconfirm base-devel sudo ccache bash
          #   update-ccache-symlinks
          #   echo 'export PATH="/usr/lib/ccache:$PATH"' | tee -a ~/.bashrc
          env: |
            PKGEXT: .pkg.tar.zst
            REPO_IDENTIFIER: ${{ steps.set-vars.outputs.repo-id }}
          shell: /bin/sh
          run: |
            echo "::set-output name=arch::$(uname -m)"
            #pacman -Syyu --noconfirm
            #pacman -S --noconfirm base-devel sudo
            echo 'auruser ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/auruser
            useradd -m auruser
            cd /tmp
            curl --output aurutils.tar.gz https://aur.archlinux.org/cgit/aur.git/snapshot/aurutils.tar.gz
            tar xf aurutils.tar.gz
            chmod -R 777 /tmp/aurutils
            cd aurutils
            sudo -u auruser makepkg --syncdeps --noconfirm
            pacman -U --noconfirm aurutils-*.pkg.*
            cp -v /tmp/aurutils/aurutils-*.pkg.* /workspace
            repo-add /workspace/${REPO_IDENTIFIER}.db.tar.gz /workspace/aurutils-*.pkg.*
            chmod -R 777 /workspace
            echo "# local repository (required by aur tools to be set up)" >> /etc/pacman.conf
            echo "[${REPO_IDENTIFIER}]" >> /etc/pacman.conf
            echo "SigLevel = Optional TrustAll" >> /etc/pacman.conf
            echo "Server = file:///workspace " >> /etc/pacman.conf
            pacman -Sy --noconfirm --no-lock
            PACKAGES=(emacs-git)
            for pkg in "${PACKAGES[@]}"; do
              echo "### Processing package: $pkg"
              echo "### Fetching package: $pkg"
              mkdir -p /tmp/build
              pushd /tmp/build
              sudo -u auruser aur fetch $pkg
              pushd /tmp/build/$pkg
              echo "### Override architecture to aarch64"
              if [[ "${{ matrix.arch }}" == "aarch64" ]]; then
                sed -i "s/^arch=.*/arch=(x86_64 aarch64)/" PKGBUILD
              elif [[ "${{ matrix.arch }}" == "armv7" ]]; then
                sed -i "s/^arch=.*/arch=(armv7)/" PKGBUILD
              fi
              sudo -u auruser aur build --noconfirm --syncdeps --clean
              popd
              popd
              cp -v /tmp/build/$pkg/$pkg-*.pkg.* /workspace
              repo-add /workspace/${REPO_IDENTIFIER}.db.tar.gz /workspace/$pkg-*.pkg.*
            done
            chmod -R 777 /workspace
          
      - name: Remove symbolic links
        run: |
          cd "${{ runner.temp }}"
          rm -v ${{ steps.set-vars.outputs.repo-id }}.db ${{ steps.set-vars.outputs.repo-id }}.files
          cp -v ${{ steps.set-vars.outputs.repo-id }}.db.tar.gz ${{ steps.set-vars.outputs.repo-id }}.db
          cp -v ${{ steps.set-vars.outputs.repo-id }}.files.tar.gz ${{ steps.set-vars.outputs.repo-id }}.files

      - name: Remove release
        uses: cb80/delrel@latest
        with:
          tag: ${{ steps.prepare.outputs.arch }}
          token: ${{ secrets.TOKEN }}

      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.prepare.outputs.arch }}
          name: Arch Linux ARM AUR Build ${{ github.run_number }} from ${{ steps.set-vars.outputs.date }} for ${{ steps.prepare.outputs.arch }}
          body: |
            To use this repository, please append the following to `/etc/pacman.conf`:
            ```
            [${{ steps.set-vars.outputs.repo-id }}]
            SigLevel = Required
            Server = https://github.com/${{ github.repository }}/releases/download/${{ steps.prepare.outputs.arch }}
            ```
          artifacts: |
            ${{ runner.temp }}/*
          draft: false
          prerelease: false
          token: ${{ secrets.TOKEN }}
